@startuml
title	DSS1.	Registro	
hide	footbox
actor	Usuario	as	user
participant ":Totseries" as TotSeries

user	->	TotSeries:iniciarRegistro()
note right TotSeries
    Pedimos al usuario sus datos personales
end note
user -> TotSeries:llegeixString(username):Bool
note right TotSeries
    Comprueba que no exista el usuario
end note
TotSeries --> user : exist

loop exist == true
    user -> TotSeries:llegeixString(username):Bool
    TotSeries --> user : exist
end
user -> TotSeries:llegeixString(password):Void
user -> TotSeries:llegeixString(nombre):Void
user -> TotSeries:llegeixString(dni):Void
user -> TotSeries:llegeixString(direccion):Void
TotSeries --> user :"Registro completado"

@enduml

