@startuml
title	DSS:4	Ver Episodio
'	ocultar	el	foot	si	son	curts,	sino	deixar-ho
'	la	comanda	es	la	seguent
hide	footbox
'definicio	d'actors
actor	Usuario	as	user
participant ":TotSeries" as TotSeries


user	->	TotSeries:verEpisodio()
'TotSeries -> user :escriu("Seleccione Serie")
user -> TotSeries:llegeixString(serieID)
'TotSeries -> user :escriu("Seleccione Temporada")
user -> TotSeries :llegeixInt(numTemporada)
'TotSeries -> user :escriu("Seleccione Episodio")
user -> TotSeries :llegeixInt(numEpisodi)
note right TotSeries
    Comprueba que exista la serie
end note
TotSeries --> user :exist
alt exist == true
    TotSeries --> user :reproduccion
    'TotSeries -> user :escriu("desea valorar?")
    user -> TotSeries :llegeixString(vullValorar)
    opt vullValorar == true
        note right user
        DS:5 Valorar Episodio
        end note
    end
else
    TotSeries --> user :escriu("No existe episodio")
end alt
@enduml
