@startuml
title	DSS:4	Ver Episodio
'	ocultar	el	foot	si	son	curts,	sino	deixar-ho
'	la	comanda	es	la	seguent
hide	footbox
'definicio	d'actors
actor	Usuario	as	user
user	->	":Totseries":verEpisodio()
":Totseries" -> user :escriu("Seleccione Serie")
user -> ":Totseries":llegeixString():String
":Totseries" -> user :escriu("Seleccione Temporada")
user -> ":Totseries" :llegeixInt():Int
":Totseries" -> user :escriu("Seleccione Episodio")
":Totseries" -> user :llegeixString():String
alt existeEpisodio == true
    ":Totseries" -> user :reproducirEpisodio()
    ":Totseries" -> user :escriu("desea valorar?")
    user -> ":Totseries" :llegeixInt():Int
    opt valorar == true
        note right user
        DS:5 Valorar Episodio
        end note
    end
else
    ":Totseries" -> user :escriu("No se puede reproducir")
end alt
@enduml
