@startuml
title	DSS: Iniciar aplicacion

hide	footbox

actor	Usuario	as	user
participant ":Totseries" as TotSeries

user	->	TotSeries:iniciaPrograma()
TotSeries --> user :Muestra Vista principal
TotSeries --> user :catalogo
TotSeries --> user :MejoresEpisodios
TotSeries --> user :MejoresEpisodios
@enduml
