@startuml
title	DSS:6	Episodios mas valorados
hide	footbox

'definicio	d'actors
actor	Usuario	as	user
user	->	":Totseries":getMejoresEpisodios()
":Totseries" -> user :Muestra episodios mas valorados

@enduml
