@startuml
title	DSS1.	Registro	
hide	footbox
actor	Usuario	as	user

user	->	":Totseries":iniciarRegistro()
":Totseries" -> user :escriu("introduzca nombre")
user -> ":Totseries":llegeixString():String
":Totseries" -> user :escriu("Introduzca password")
user -> ":Totseries" :llegeixString():String
":Totseries" -> user :escriu("Introduzca ID")
user -> ":Totseries" :llegeixString():String
":Totseries" -> user :escriu("Introduzca fecha de nacimiento")
user -> ":Totseries" :llegeixString():String
":Totseries" -> user :escriu("Introduzca pais de nacimiento")
user -> ":Totseries" :llegeixString():String

loop ID == existente
    ":Totseries" -> user :escriu("Introduzca ID")
    user -> ":Totseries" :llegeixString():String
end
":Totseries" -> user :escriu("Usuario Creado")
@enduml

