@startuml
title	DSS1.	Registro	
hide	footbox
actor	Usuario	as	user
participant ":Totseries" as TotSeries

user	->	TotSeries:pulsaBotonRegistrarse()
TotSeries --> user: Mostrar Vista registro

note right TotSeries
    boolean registrado=False
    boolean admin = False
end note
loop ! pulsaBotonCancelar() and !registrado
    user -> TotSeries:rellenarFormulario(username, password, \nnombre, dni, pais)
    opt marcaCasillaAdmin()
    user -> TotSeries: marcaCasillaAdmin()
        note right TotSeries
            admin = !admin
        end note
    end opt
    opt pulsaBotonRegistrar()
    user -> TotSeries:pulsaBotonRegistrar():Boolean
        note right TotSeries
            Comprueba que no exista el usuario
        end note
        TotSeries --> user : exist
        alt !exist
            alt admin
                TotSeries --> user :Alert("Administrador Registrado")
            else 
                TotSeries --> user :Alert("Cliente Registrado")
            end alt
            note right TotSeries
                registrado=True
            end note
            
        else
            TotSeries --> user :"Usuario ya existe"
        end alt
    end opt
end loop
TotSeries --> user: Retorna a la vista principal
@enduml

