@startuml
title	DSS:6	Episodios mas valorados
'	ocultar	el	foot	si	son	curts,	sino	deixar-ho
'	la	comanda	es	la	seguent
hide	footbox
'definicio	d'actors
actor	Usuario	as	user
user	->	":Totseries":getMejoresEpisodios():String
":Totseries" --> user :listaMejoresEpisodios

@enduml
