@startuml
title	DSS5 Valoracion	
hide	footbox

actor	Usuario	as	user
participant ":Totseries" as Totseries

'Totseries -> user: escriu("Introduzca valoracion")
user -> Totseries: llegeixInt(valoracion):String
Totseries --> user: "Se realizo la valoracion"


@enduml
