@startuml
title	DSS5 Valoracion	
hide	footbox

actor	Usuario	as	user
participant ":Totseries" as Totseries

Totseries -> user: escriu("Introduzca valoracion")
user -> Totseries: llegeixInt():Int
Totseries -> user: escriu("Se realizo la valoracion")


@enduml
