/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries.Vista;

import totseries.Controlador.TotSeries;
import totseries.Modelo.Media.Episodio;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Abel
 */
public class EpisodioJDialog extends javax.swing.JDialog {
    Episodio episodio;
    TotSeries controlador;
    boolean valorado;
    /**
     * Creates new form EpisodioJDialog
     */
    public EpisodioJDialog(java.awt.Frame parent, boolean modal,Episodio episodio,String descripcion,TotSeries controlador) {
        super(parent, modal);
        initComponents();
        this.episodio = episodio;
        this.jTextFieldNombre.setText(this.episodio.getTitulo());
        this.jTextFieldDescripcion.setText(descripcion);
        this.jTextField3.setVisible(false);
        this.jProgressBarDuracion.setVisible(false);
        this.jButtonValorar.setVisible(false);
        this.jProgressBarDuracion.setMaximum(5);
        this.controlador = controlador;
        this.valorado = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButtonValorar = new javax.swing.JButton();
        jButtonReproducir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jProgressBarDuracion = new javax.swing.JProgressBar();
        jTextFieldValoracion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.setText("Episodio");

        jTextFieldDescripcion.setEditable(false);
        jTextFieldDescripcion.setText("Descripcion");

        jTextField3.setEditable(false);
        jTextField3.setText("Duracion");

        jButtonValorar.setText("Valorar");
        jButtonValorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValorarActionPerformed(evt);
            }
        });

        jButtonReproducir.setText("Reproducir");
        jButtonReproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReproducirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDescripcion)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonReproducir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonValorar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jProgressBarDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3)
                    .addComponent(jProgressBarDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValorar)
                    .addComponent(jButtonReproducir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jTextFieldValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.setVisible(false);
        this.jProgressBarDuracion.setVisible(true);
        for (int i = 0; i < 5; i++) {
            try {
                //Pausas de 1 segundo
                Thread.sleep(1000);
                this.jProgressBarDuracion.setValue(i);
            } catch (InterruptedException ex) {
                Logger.getLogger(EpisodioJDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.jButtonValorar.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReproducirActionPerformed
        this.jTextField3.setVisible(true);
        
    }//GEN-LAST:event_jButtonReproducirActionPerformed

    private void jButtonValorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValorarActionPerformed
        int valoracion = Integer.parseInt(this.jTextFieldValoracion.getText());
        if( valoracion > 0 && valoracion <= 5 && !this.valorado){
            this.controlador.valorarEpisodio(this.episodio, valoracion);
            this.valorado = true;
        }else
           JOptionPane.showMessageDialog(this, "Introduzca una valoracion entre el 1 y el 5","Error",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButtonValorarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonReproducir;
    private javax.swing.JButton jButtonValorar;
    private javax.swing.JProgressBar jProgressBarDuracion;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldValoracion;
    // End of variables declaration//GEN-END:variables
}
