/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries.Vista;

import static java.lang.Thread.sleep;
import java.util.Observer;
import totseries.Controlador.TotSeries;
import totseries.Modelo.Media.Episodio;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author Abel
 */
public class EpisodioJDialog extends javax.swing.JDialog {

    Episodio episodio;
    TotSeries controlador;
    boolean valorado;
    boolean en_reproduccion=false;

    /**
     * Creates new form EpisodioJDialog
     */
    public EpisodioJDialog(java.awt.Frame parent, boolean modal, Episodio episodio, TotSeries controlador) {
        super(parent, modal);
        initComponents();
        this.episodio = episodio;
        episodio.addObserver((Observer) parent);
        this.jTextFieldNombre.setText(this.episodio.getTitulo());
        this.jTextFieldDescripcion.setText(episodio.getDescripcion());
        this.jProgressBarDuracion.setVisible(true);
        this.jButtonValorar.setVisible(false);
        this.jTextFieldValoracion.setVisible(false);
        this.jButtonValorar.setVisible(false);
        this.jProgressBarDuracion.setMaximum(5);
        this.controlador = controlador;
        this.valorado = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonValorar = new javax.swing.JButton();
        jButtonReproducir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jProgressBarDuracion = new javax.swing.JProgressBar();
        jTextFieldValoracion = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonValorar.setText("Valorar");
        jButtonValorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValorarActionPerformed(evt);
            }
        });

        jButtonReproducir.setText("Reproducir");
        jButtonReproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReproducirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jProgressBarDuracion.setForeground(new java.awt.Color(204, 0, 102));
        jProgressBarDuracion.setMaximum(5);
        jProgressBarDuracion.setRequestFocusEnabled(false);
        jProgressBarDuracion.setString("0");
        jProgressBarDuracion.setVerifyInputWhenFocusTarget(false);

        jTextFieldValoracion.setText("0");
        jTextFieldValoracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValoracionActionPerformed(evt);
            }
        });

        jTextFieldNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTextFieldNombre.setText("Episodio");

        jTextFieldDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jTextFieldDescripcion.setText("Descripcion");
        jTextFieldDescripcion.setToolTipText("");
        jTextFieldDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jTextFieldDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextFieldDescripcion.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextFieldDescripcion.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jTextFieldDescripcion.setName(""); // NOI18N

        jTextField3.setText("Duracion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonCancelar)
                                .addGap(50, 50, 50)
                                .addComponent(jButtonReproducir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonValorar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextField3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jProgressBarDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTextFieldNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBarDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReproducir)
                    .addComponent(jButtonValorar)
                    .addComponent(jTextFieldValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReproducirActionPerformed
        controlador.empezarReproduccion(episodio);
        for (int i = 0; i <= 5; i++) {

            this.jProgressBarDuracion.setValue(i);
            this.paint(this.getGraphics());
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(EpisodioJDialog.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        controlador.finalizarReproduccion(episodio, true);
        this.jTextFieldValoracion.setVisible(true);
        this.jButtonValorar.setVisible(true);
        this.jButtonReproducir.setEnabled(false);
    }//GEN-LAST:event_jButtonReproducirActionPerformed

    private void jButtonValorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValorarActionPerformed
        int valoracion = Integer.parseInt(this.jTextFieldValoracion.getText());
        if (!this.valorado) {
            if (valoracion >= 0 && valoracion <= 5) {
                this.controlador.valorarEpisodio(this.episodio, valoracion);
                JOptionPane.showMessageDialog(this, "A valorado el episodio!");
                this.valorado = true;
            } else {
                JOptionPane.showMessageDialog(this, "Introduzca una valoracion entre el 1 y el 5", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ya se ha valorado el episodio", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonValorarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (en_reproduccion){
            en_reproduccion=false;
            controlador.finalizarReproduccion(episodio, false);
        }
        episodio.deleteObservers();
    }//GEN-LAST:event_formWindowClosing

    private void jTextFieldValoracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValoracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValoracionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonReproducir;
    private javax.swing.JButton jButtonValorar;
    private javax.swing.JProgressBar jProgressBarDuracion;
    private javax.swing.JLabel jTextField3;
    private javax.swing.JLabel jTextFieldDescripcion;
    private javax.swing.JLabel jTextFieldNombre;
    private javax.swing.JTextField jTextFieldValoracion;
    // End of variables declaration//GEN-END:variables
}
