/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries.Vista;

import totseries.Controlador.TotSeries;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static totseries.Main.cargarDatos;
import totseries.Modelo.Media.Episodio;
import totseries.Modelo.Media.Serie;
import totseries.Modelo.Media.Temporada;
import totseries.Parser.TotSeriesDataManager;

/**
 *
 * @author Abel
 */
public class Vista extends javax.swing.JFrame {

    TotSeries controlador;

    /**
     * Creates new form Vista
     */
    public Vista(TotSeries controlador) {
        initComponents();
        this.controlador = controlador;
        this.jMenuAdministrador.setVisible(false);
        this.jMenuCliente.setVisible(false);
        this.jListTemporadas.setVisible(false);
        this.jListEpisodios.setVisible(false);
        this.actualizarMasValorados();
        this.actualizarCatalogo();
        
        /*
        this.jMenuItemAsignarVIP.setVisible(false);
        this.jMenuItemCargarFichero.setVisible(false);
        this.jListTemporadas.setVisible(false);
        this.jListEpisodios.setVisible(false);
        this.jListValorados.setVisible(false);
        this.jListVisitados.setVisible(false);
        this.jTextFieldTemporadas.setVisible(false);
        this.jTextFieldEpisodios.setVisible(false);
        this.jTextFieldValorados.setVisible(false);
        this.jTextFieldVisitados.setVisible(false);
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListCatalogo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTemporadas = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListEpisodios = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListVisitados = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListValorados = new javax.swing.JList<>();
        jTextFieldVisitados = new javax.swing.JTextField();
        jTextFieldValorados = new javax.swing.JTextField();
        jTextFieldCatalogo = new javax.swing.JTextField();
        jTextFieldTemporadas = new javax.swing.JTextField();
        jTextFieldEpisodios = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemRegistrar = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemDesloguear = new javax.swing.JMenuItem();
        jMenuAdministrador = new javax.swing.JMenu();
        jMenuItemCargarFichero = new javax.swing.JMenuItem();
        jMenuItemAsignarVIP = new javax.swing.JMenuItem();
        jMenuItemDeslogearAdmin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListCatalogo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListCatalogoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListCatalogo);

        jListTemporadas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListTemporadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTemporadasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListTemporadas);

        jListEpisodios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListEpisodios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListEpisodiosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListEpisodios);

        jListVisitados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jListVisitados);

        jListValorados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(jListValorados);

        jTextFieldVisitados.setEditable(false);
        jTextFieldVisitados.setText("  Más Visitados");
        jTextFieldVisitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVisitadosActionPerformed(evt);
            }
        });

        jTextFieldValorados.setEditable(false);
        jTextFieldValorados.setText("   Valorados");

        jTextFieldCatalogo.setEditable(false);
        jTextFieldCatalogo.setText("       Series");
        jTextFieldCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCatalogoActionPerformed(evt);
            }
        });

        jTextFieldTemporadas.setEditable(false);
        jTextFieldTemporadas.setText("   Temporadas");

        jTextFieldEpisodios.setEditable(false);
        jTextFieldEpisodios.setText("     Episodios");

        jMenuUsuario.setText("Usuario");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });

        jMenuItemLogin.setText("Login");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemLogin);

        jMenuItemRegistrar.setText("Registrar");
        jMenuItemRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemRegistrar);

        jMenuBar1.add(jMenuUsuario);

        jMenuCliente.setText("Cliente");

        jMenuItemDesloguear.setText("Desloguear");
        jMenuItemDesloguear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDesloguearActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemDesloguear);

        jMenuBar1.add(jMenuCliente);

        jMenuAdministrador.setText("Administrador");

        jMenuItemCargarFichero.setText("Cargar Fichero");
        jMenuItemCargarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarFicheroActionPerformed(evt);
            }
        });
        jMenuAdministrador.add(jMenuItemCargarFichero);

        jMenuItemAsignarVIP.setText("AsignarVIP");
        jMenuItemAsignarVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAsignarVIPActionPerformed(evt);
            }
        });
        jMenuAdministrador.add(jMenuItemAsignarVIP);

        jMenuItemDeslogearAdmin.setText("Desloguear");
        jMenuItemDeslogearAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeslogearAdminActionPerformed(evt);
            }
        });
        jMenuAdministrador.add(jMenuItemDeslogearAdmin);

        jMenuBar1.add(jMenuAdministrador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEpisodios, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldVisitados, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldValorados, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldVisitados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldEpisodios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldValorados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCatalogoActionPerformed

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        LoginJDialong login = new LoginJDialong(this, true, this.controlador);
        login.setVisible(true);
        if(this.controlador.isloggedAdmin()){
            this.jMenuAdministrador.setVisible(true);
            this.jMenuUsuario.setVisible(false);
        }else if (this.controlador.islogged()){
            this.jMenuCliente.setVisible(true);
            this.jMenuUsuario.setVisible(false);
        }
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed

    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuItemRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarActionPerformed
        RegistroJDialog registro = new RegistroJDialog(this, true, this.controlador);
        registro.setVisible(true);

    }//GEN-LAST:event_jMenuItemRegistrarActionPerformed

    private void jListCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListCatalogoMouseClicked
        this.vaciarListaEpisodios();
        this.jTextFieldEpisodios.setVisible(false);
        this.jListEpisodios.setVisible(false);
        this.actualizarTemporadas();
    }//GEN-LAST:event_jListCatalogoMouseClicked

    private void jListTemporadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTemporadasMouseClicked
        this.vaciarListaEpisodios();
        this.jTextFieldEpisodios.setVisible(true);
        this.jListEpisodios.setVisible(true);
        this.actualizarEpisodios();
    }//GEN-LAST:event_jListTemporadasMouseClicked

    private void jListEpisodiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListEpisodiosMouseClicked
        if (!controlador.islogged()) {
            JOptionPane.showMessageDialog(this, "Tienes que estar registrado para poder ver videos");
            return;
        }
        EpisodioJDialog repro = new EpisodioJDialog(
                this, true, this.jListEpisodios.getSelectedValue(), this.controlador);
        repro.setVisible(true);
        
    }//GEN-LAST:event_jListEpisodiosMouseClicked

    private void jMenuItemCargarFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarFicheroActionPerformed
        JOptionPane.showMessageDialog(this, "Sin Implementar", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jMenuItemCargarFicheroActionPerformed

    private void jMenuItemAsignarVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAsignarVIPActionPerformed
        JOptionPane.showMessageDialog(this, "Sin Implementar", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jMenuItemAsignarVIPActionPerformed

    private void jMenuItemDesloguearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDesloguearActionPerformed
        this.controlador.logout();
        this.jMenuCliente.setVisible(false);
        this.jMenuUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemDesloguearActionPerformed

    private void jMenuItemDeslogearAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeslogearAdminActionPerformed
        this.controlador.logout();
        this.jMenuAdministrador.setVisible(false);
        this.jMenuUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemDeslogearAdminActionPerformed

    private void jTextFieldVisitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVisitadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVisitadosActionPerformed
    private void actualizarCatalogo(){
        DefaultListModel model = new DefaultListModel();
        model.clear();
        this.jListTemporadas.setVisible(true);
        this.jListEpisodios.setVisible(false);

        controlador.getSeries().forEach((serie) -> {
            model.addElement(serie);
        });
        
        this.jListCatalogo.setModel(model);
    }

    private void actualizarTemporadas() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        this.jListEpisodios.setVisible(true);
        
        this.jListCatalogo.getSelectedValue().getTemporadas().forEach((temporada) -> {
            model.addElement(temporada);
        });
        this.jListTemporadas.setModel(model);
    }
    
    private void actualizarMasValorados() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        
        
        //No acoplar!!
        controlador.getCatalogo().getEpisodiosMasValorados().forEach((temporada) -> {
            model.addElement(temporada);
        });
        this.jListValorados.setModel(model);
    }

    private void actualizarEpisodios() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        
        this.jListTemporadas.getSelectedValue().getEpisodios().forEach((episodio) -> {
            model.addElement(episodio);
        });
        
        this.jListEpisodios.setModel(model);
    }

    private void vaciarListaEpisodios() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        this.jListEpisodios.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            TotSeries controlador = cargarDatos(TotSeries.getInstance());

            @Override
            public void run() {
                new Vista(controlador).setVisible(true);
            }
        });
    }

    public static TotSeries cargarDatos(TotSeries tot_Series) {
        TotSeriesDataManager dataManager = new TotSeriesDataManager();
        dataManager.obtenirDades("data/TotSeries.xml");
        tot_Series = dataManager.cargarDatos(tot_Series);
        return tot_Series;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Serie> jListCatalogo;
    private javax.swing.JList<Episodio> jListEpisodios;
    private javax.swing.JList<Temporada> jListTemporadas;
    private javax.swing.JList<Episodio> jListValorados;
    private javax.swing.JList<Episodio> jListVisitados;
    private javax.swing.JMenu jMenuAdministrador;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuItemAsignarVIP;
    private javax.swing.JMenuItem jMenuItemCargarFichero;
    private javax.swing.JMenuItem jMenuItemDeslogearAdmin;
    private javax.swing.JMenuItem jMenuItemDesloguear;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemRegistrar;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextFieldCatalogo;
    private javax.swing.JTextField jTextFieldEpisodios;
    private javax.swing.JTextField jTextFieldTemporadas;
    private javax.swing.JTextField jTextFieldValorados;
    private javax.swing.JTextField jTextFieldVisitados;
    // End of variables declaration//GEN-END:variables
}
