@startuml
title	DS:6	Ver Episodios mas valorados
hide	footbox

actor Usuario
participant ":TotSeries" as TotSeries
participant ":Catalogo" as Catalogo
participant ":Serie" as Serie
participant ":Temporada" as Temporada
participant ":Episodio" as Episodio
participant ":Consola" as Consola

Usuario -> TotSeries:getMejoresEpisodios():Void
activate TotSeries
TotSeries -> Catalogo:getMejoresEpisodios():String
activate Catalogo


note right Catalogo
    listaSerie : String
    listaSerie := ""
end note

loop for serie in series
    note right Catalogo
        lista_episodio += serie.getNombre():String
    end note
    Catalogo -> Serie:getMejoresEpisodios():String
    activate Serie


    note right Serie
    lista_episodio : String
    lista_episodio := ""
    end note

    loop for temporada in temporadas
        note right Serie
        lista_episodio += temporada.getnumero():int
        end note
        Serie -> Temporada:getMejoresEpisodios():String
        activate Temporada


        note right Temporada
            lista_episodio: String
            lista_episodio:= ""
        end note

        loop for episodio in episodios
            Temporada -> Episodio:getValoracionMedia():Int
            activate Episodio
            Episodio --> Temporada:valoracion
            deactivate Episodio


            opt valoracion >= 4
                Temporada -> Episodio:toString():String
                activate Episodio
                Episodio --> Temporada:text
                deactivate Episodio

                note right Temporada
                    lista_episodio += text
                end note

            end opt
        end loop
        Temporada --> Serie:lista_episodio
        deactivate Temporada


        note right Serie
            lista_episodio += lista_episodio
        end note

    end loop
    Serie --> Catalogo:lista_episodio
    deactivate Serie

     note right Catalogo
        lista_episodio += lista_episodio
    end note
end loop
Catalogo --> TotSeries:lista_episodio
deactivate Catalogo

TotSeries -> Consola : escriu(lista_episodio):Void
activate Consola
deactivate Consola
deactivate TotSeries
@enduml
