@startuml

left to right direction

'title Diagrama de Dominio para TotSeries

namespace Controlador {
    class Totseries{
    -Cliente actualCliente
    ==
    +void reproducirEpisodio(String idSerie, int idtemporada, int idEpisodio)
    +void valorarEpisodio(String serie_id,int temporada_id,int episodio_id,int puntuacion)
    +String verCatalogo()
    +String verTemporadas(String idSerie)
    +String verEpisodios(String idSerie, int idTemporada)
    +boolean hasUsuario(String username)
    +void registrar(String username,String password,String nombre,String pais,Date fNacimiento)
    +void verMejoresEpisodios()
    }
    
}

namespace java.util {
    class Scanner
}

namespace Vista {

    class Menu{
        -TotSeries totSeries
        ==
        +void run()
        +void printMenu()
    }
    class Consola{
    ==
    +void escriu(String s)
    +void escriu(Int i)
    +void escriu(float f)
    +int llegeixInt()
    +string llegeixString()
    }

    Menu "1" - "1" Consola : usa >
}

namespace Model {

    
    class Registro{
    ==
    +boolean hasUsuario(String username)
    +registrar(String nom, String dni, String adreca, String usuari, String password)
    }

    class Usuario {
        - String id
        - String username
        - String password
        - String nombre
    }
    class Cliente {
        - String pais
        - Date nacimiento
        - Boolean vip
        - String dni
        - String direccion
        ==
        + Factura getLastFactura()
        + addVisualizacion()
    }
    class Administrador{
    }

    class Factura{
        -float total
        -Date fecha
        -int visualizaciones
        ==
        + addVisualizacion()
    }
    
    class Catalogo{
        ==
        + String getMejoresEpisodios()
        + void addSerie(Serie serie)
        + boolean existeEpisodio(String idSerie, int idTemporada,int idEpisodio)
        + Episodio getEpisodio(String idSerie,int idTemporada,int idEpisodio)
        + String verTemporadas(String idSerie)
        + String verEpisodios(String idSerie, int idTemporada)
        + String toString()
        + Serie getLastSerie()
    }
    class Temporada{
        - int id
        - int numEpisodis
        ==
        + String toString()
        + String getMejoresEpisodios()
        + boolean existeEpisodio(int idEpisodio)
        + Episodio getEpisodio(int episodio)
        + void addEpisodio(Episodio espisodio)
        + int size()
        + String verEpisodios()
        + void addEpisodio(Episodio)
    }

    class Serie{
        -String id
        -String nombre
        -String descripcion
        ==
        + String toString()
        + String getMejoresEpisodios()
        + boolean existeEpisodio(int temporada, int idEpisodio)
        + boolean equals(String idSerie)
        + Temporada getLastTemporada()
        + void addTemporada(Temporada temporada)
        + Episodio getEpisodio(int idTemporada,int idEpisodio)
        + String verEpisodios(int idTemporada)
        + String verTemporadas()
        + Temporada getLastTemporada()
        + boolean hasTemporada(int idTemporada)
    }
    class Valoracion{
        -String usuario
        -int puntuacion
        -Date fecha
    }
    
    class Episodio {
        - int id
        - String titulo
        - String duracion
        - String idioma
        - String descripcion
        - float promedio
        - Date fecha
        - String descripción
        ==
        + String toString()
        + void setPromedio()
        + void addValoracion(Valoracion valoracion)
    }

    
    abstract class Artista {
        - String id
        - String nombre
        - String nacionalidad
    }

    class Productora {
        - string nombre
        - String id
        - Date fCreacion
    }

    class Actor{
    }
    class Director{
    }

    Registro "1" -- "0..* | usuarios" Cliente : contine >
    Registro "1" -- "0..* | administradores" Administrador : contine >

    Usuario <|-- Cliente
    Usuario <|-- Administrador
    Cliente "1" -- "0..* | facturas" Factura : tiene >  
    Artista  <|-- Actor
    Artista  <|-- Director

    Catalogo "1" *-- "1..* | series" Serie : consta >
    Serie "1" *-- "1..* | temporadas" Temporada : consta >
    Serie "1..*" - "1..* | artistas" Artista : tiene >
    Serie "1..*" - "1..* | productoras" Productora : tiene >
    Temporada "1" *- "1..* | episodios" Episodio : consta >
    Episodio "1" - "0..* | valoraciones" Valoracion : tiene >

}

Controlador.Totseries "1" -- "1 | catalogo" Model.Catalogo : tiene >
Controlador.Totseries "1" -- "1" Vista.Consola : usa >
Controlador.Totseries "1" -- "1 | registro" Model.Registro : tiene >
Controlador.Totseries "1" -- "1" Vista.Menu : Usa
java.util.Scanner "-sc | 1" <-- "1" Vista.Consola : Usa 
@enduml
