@startuml

left to right direction

'title Diagrama de Dominio para TotSeries

namespace Controlador {
    class Totseries{
    ==
    +void verEpisodio(String idSerie, int idtemporada, String idEpisodio)
    +void verCatalogo()
    +void registrar(String username,String password,String nombre,String pais,Date fNacimiento)
    +void verMejoresEpisodios()
    }
    
}

namespace java.util {
    class Scanner
}

namespace Vista {
    class Consola{
    ==
    +void escriu(String s)
    +void escriu(Int i)
    +void escriu(float f)
    +int llegeixInt()
    +string llegeixString()
    }
}

namespace Model {

    
    class Registro{
    ==
    +boolean hasUsuario(string username)
    +registrar(String username,String password,String nombre,String pais,Date fNacimiento)
    }

    class Usuario {
        - String username
        - String password
        - String nombre
        - String id
    }
    class Cliente {
        - String pais
        - Date nacimiento
        - Boolean VIP
        ==
    }
    class Administrador{
        ==
    }

    class Factura{
        -float total
        -Date fecha
        -int visualizaciones
    }
    
    class Catalogo{
        ==
        +String toString()
        +String getMejoresEpisodios()
        +void addSerie(Serie serie)
        +bool existeEpisodio(String idSerie, int idTemporada,String idEpisodio)
        +Episodio verEpisodio(String idSerie,int idTemporada,String idEpisodio)
    }
    class Temporada{
        -int idTemporada
        ==
        +String toString()
        +String getMejoresEpisodios()
        +bool existeEpisodio(String idEpisodio)
        +Episodio verEpisodio(int episodio)
        +void addEpisodio(Episodio espisodio)
        +int size()
    }

    class Serie{
        -String id
        -String nombre
        -String descripcion
        ==
        +String toString()
        +String getMejoresEpisodios()
        +bool existeEpisodio(int temporada, String idEpisodio)
        +bool equals(String idSerie)
        +Temporada getLastTemporada()
        +void addTemporada(Temporada temporada)
        +Episodio verEpisodio(int idTemporada,String idEpisodio) 
    }
    class Valoracion{
        -String usuario
        -int puntuacion
        -Date fecha
    }
    
    class Episodio {
        -String titulo
        -String duracion
        -String idioma
        -String descripcion
        -float promedio
        -Date fecha
        -String descripción
        -String id
        ==
        +Episodio verEpisodio()
        +String toString()
        +bool equals(String idEpisodio)
    }

    
    abstract class Artista {
        -String id
        -String nombre
        -String nacionalidad
    }

    class Productora {
        -string nombre
        -String id
        -Date fCreacion
    }

    class Actor
    class Director

    Registro "1" -- "0..* | usuarios" Cliente : contine >
    Registro "1" -- "0..* | administradores" Administrador : contine >

    Usuario <|-- Cliente
    Usuario <|-- Administrador
    Cliente "1" -- "0..* | facturas" Factura : tiene >  
    Artista  <|-- Actor
    Artista  <|-- Director

    Catalogo "1" *-- "1..* | series" Serie : consta >
    Serie "1" *-- "1..* | temporadas" Temporada : consta >
    Serie "1..*" - "1..* | artistas" Artista : tiene >
    Serie "1..*" - "1 | productora" Productora : tiene >
    Temporada "1" *- "1..* | episodios" Episodio : consta >
    Episodio "1" - "0..* | valoraciones" Valoracion : tiene >

}

Controlador.Totseries "1" -- "1 | catalogo" Model.Catalogo : tiene >
Controlador.Totseries "1" -- "1 | registro" Model.Registro : tiene >
Controlador.Totseries "1" -- "1" Vista.Consola : Usa
java.util.Scanner "-sc | 1" <-- "1" Vista.Consola : Usa 
@enduml
