@startuml

title	DS:3 Ver Catalogo
hide	footbox

actor	Cliente
participant ":Menu" as Menu
participant ":TotSeries" as TotSeries
participant ":Catalogo" as Catalogo
participant ":Serie" as Serie
participant ":Consola" as Consola


note right Cliente
    selecciona el caso 3
endnote

Cliente -> Menu
activate Menu
Menu -> TotSeries:verCatalogo(): String
activate TotSeries
TotSeries -> Catalogo:toString():String
activate Catalogo
note right Catalogo
    lista_series : String
    lista_series := ""
end note


loop For serie in catalogo
    Catalogo -> Serie:toString():String
    activate Serie
    Serie --> Catalogo:text
    deactivate Serie
    note right Catalogo
        lista_series += text
    endnote
end

opt series.size()==0
    note right Catalogo
        lista_series = "No hay series"
    endnote
end
Catalogo --> TotSeries: lista_series
deactivate Catalogo

TotSeries --> Menu: lista_series

Menu -> Consola: escriu(lista_series):Void
activate Consola



@enduml
