
@startuml
title	DS:4.1	Ver Episodio
hide	footbox

participant ":TotSeries" as TotSeries
participant ":Catalogo" as Catalogo
participant ":Serie" as Serie
participant ":Temporada" as Temporada
participant ":Episodio" as Episodio
participant "cliente:Cliente" as cliente


activate TotSeries
TotSeries -> Catalogo:existeEpisodio(idSerie:String,\n idTemporada:int,idEpisodio:int):boolean


activate Catalogo 
note right Catalogo
        exist:boolean
        exist := false
    end note
loop For serie in series

    Catalogo -> Serie:getId():String
    activate Serie
    Serie --> Catalogo:id
    deactivate Serie


    opt id.equals(idSerie):boolean
    Catalogo -> Serie:exist:=existeEpisodio(idTemporada:int, \nidEpisodio:int):boolean
    activate Serie
    note right Serie
        exist:boolean
        exist := false
    end note
    
    loop For temporada in temporadas
        Serie -> Temporada:getId():Int
        activate Temporada
        Temporada --> Serie:id
        deactivate Temporada

        opt idTemporada==id
        Serie -> Temporada:exist:=existeEpisodio(idEpisodio):boolean
        activate Temporada
        note right Temporada
            exist:boolean
            exist := false
        end note

        loop For episodio in episodios
            Temporada -> Episodio:getId():Int
            activate Episodio
            Episodio --> Temporada:id
            deactivate Episodio


            opt idEpisodio==id
                note right Temporada
                    exist := true
                end note
            end opt
        end loop
        Temporada --> Serie:exist
        end opt
    end loop
    deactivate Temporada
    Serie --> Catalogo:exist
    end opt
end loop

deactivate Serie
Catalogo --> TotSeries:exist
deactivate Catalogo
deactivate TotSeries
@enduml
