@startuml
title		Valorar
hide	footbox

actor	Usuario as usuario
participant "vista:EpisodioJDialog" as vista
participant "controlador:TotSeries" as totseries
participant "episodio:Episodio" as episodio
participant "registro:Registro" as registro
participant "logged:Usuario" as logged
participant ":Valoracion" as valoracion

usuario -> vista : clickBotonValorar
activate vista
note right vista
    valorado := boolean
    valoracion := int
end note
alt !valorado  
    alt valoracion >= 0 && valoracion <= 5
        
        
        vista -> totseries : valorarEpisodio(\nEpisodio episodio,\nint valoracion)
        activate totseries
        
        totseries -> registro : getLogged():Usuario
        activate registro
        registro -->totseries : logged
        deactivate registro
        totseries -> logged : getId():String
        activate logged
        logged --> totseries : id
        deactivate logged
        
        
        totseries -> episodio : addValoracion(\nString id,\n float puntuacion)
        activate episodio
        episodio -> valoracion : new Valoracion(String id, float puntuacion)
        activate valoracion
        valoracion -->episodio: valoracion
        deactivate valoracion
        episodio ->episodio: valoraciones.add(val)
        episodio ->episodio: notifyObservers(1)
        episodio ->episodio: setChanged();
        episodio --> totseries
        deactivate episodio
        totseries -->vista
        deactivate totseries
    else 
        note right vista
            se notifica al usuario por un mensage
            que la valoracion no se encuentra dentro
            del rango de 0 y 5
        end note
    end alt
else
    note right vista
        se notifica al usuario por un mensage
        que ya se ha valorado el episodio
    end note
end alt
vista --> usuario
deactivate vista
@enduml
