@startuml
title		Registro
hide	footbox

actor	Usuario as usuario
participant "vista:RegistroJDialog" as vista
participant "controlador:TotSeries" as totseries
participant "registro:Registro" as registro
participant "usuario:Usuario" as user

usuario -> vista : ClickBotonRegistrar
activate vista
note right vista
    boolean := registro
    checkBox= getState() //Indica si es administrador
end note
alt checkbox
    vista -> totseries : Registro (\nString usuario,String password,\n String nombre):boolean
    activate totseries

    totseries -> registro : hasUsuario(String new_usuario):boolean
    activate registro
    loop foreach(Usuario user in usuarios)
        registro -> user: getUsername()
        activate user
        user --> registro: username
        deactivate user
        opt new_usuario==username
            registro --> totseries: exist=:true
            end opt
    end loop
    registro --> totseries: exist=:false
    deactivate registro

    opt !exist
        note right totseries
            Diagrama de Secuencia RegistroAdmin
        end note
       end opt

    totseries --> vista : registro := boolean
    deactivate totseries
else
    vista -> totseries : Registro (\nString usuari,String password,\n String nom, String dni,\n String adreca): boolean
    activate totseries

    totseries -> registro : hasUsuario(String new_usuario):boolean
    activate registro
    loop foreach(Usuario user in usuarios)
        registro -> user: getUsername()
        activate user
        user --> registro: username
        deactivate user
        opt new_usuario==username
            registro --> totseries: exist=:true
            end opt
    end loop
    registro --> totseries: exist=:false
    deactivate registro

    opt !exist
        note right totseries
            Diagrama de Secuencia RegistroCliente
        end note
       end opt
    totseries --> vista : registro := boolean
    deactivate totseries
end alt

alt registro
    note right vista
    Se le notifica al usuario que se ha
    registrado satisfactoriamente
    end note
else
    note right vista
    se le notifica al usuario que no se
    ha podida realizar el registro
    end note
end alt
vista --> usuario
deactivate vista

@enduml