
@startuml
title	DS:4	Ver Episodio
hide	footbox

actor	Usuario
participant ":Menu" as Menu

participant ":TotSeries" as TotSeries
participant "actualCliente:Cliente" as cliente

participant ":Catalogo" as Catalogo
participant ":Factura" as factura
participant ":Serie" as Serie
participant ":Temporada" as Temporada
participant ":Episodio" as Episodio
participant ":Consola" as Consola



note right Usuario
            Selecciona el caso de uso 4
        end note
Usuario -> Menu
activate Menu
Menu -> TotSeries:reproducirEpisodio(serieId:String, \ntemporadaId:int, episodioId:int):boolean
activate TotSeries

note right TotSeries
            UC4.1 Existe Episodio
        end note

TotSeries -> Catalogo: existeEpisodio(serieId:String, \ntemporadaId:int, episodioId:int)
activate Catalogo
Catalogo --> TotSeries:exist
deactivate Catalogo
'
opt exist == true
    TotSeries -> Catalogo:getEpisodio(serieId:String, \ntemporadaId:int, episodioId:int):Episodio
    activate Catalogo
    Catalogo -> Serie:getEpisodio(temporadaId:int, \nepisodioId:int):Episodio
    activate Serie
    Serie -> Temporada:getEpisodio(episodio:int):Episodio
    activate Temporada
    Temporada->Episodio:getEpisodio():Episodio
    activate Episodio
    Episodio-->Temporada:episodio
    deactivate Episodio
    Temporada-->Serie:episodio
    deactivate Temporada
    Serie --> Catalogo:episodio
    deactivate Serie
    Catalogo --> TotSeries:episodio
    deactivate Catalogo
    TotSeries -> Consola : escriu("Reproduciendo"):Void
    ... Viendo episodio ...
    TotSeries->cliente:addVisualizacion():Void
    activate cliente
    cliente->factura:addVisualizacion():Void
    activate factura
    deactivate factura
    deactivate cliente
end opt
    TotSeries --> Menu : exist
    deactivate TotSeries
    opt exist==True
        Menu->Consola:escriure("Valorar episodio?"):Void
        Menu -> Consola:llegirString():String
        Consola --> Menu:opcion

        opt opcion == true
            note right Menu
            DS5. Valoracion
            end note
         end opt
     end opt
deactivate TotSeries
@enduml
