@startuml
title	DS: Registrarse UC1
hide	footbox

actor Cliente
participant ":Menu" as Menu
participant ":Consola" as Consola
participant ":TotSeries" as TotSeries
participant ":Registro" as Registro
participant ":Cliente" as Usuario
participant "nuevo:Cliente" as nUsuario

Cliente -> Menu
activate Menu
loop totSeries.hasUsuario(username)== false
    Menu->Consola:escriu("Introduzca un nuevo username, este ya esta cogido: ")
    activate Consola
    Menu->Consola:llegeixString():String
    Consola->Menu:usern:String
    deactivate Consola
    note right Menu
        username:=usern
    end note
end loop
Menu -> TotSeries:registrar(username,password,nombre,dni,direccion):Void
activate TotSeries
TotSeries -> Registro:registrar(nom,dni,adreca,usuari,password)
activate Registro
create nUsuario
activate nUsuario
Registro -> nUsuario:Cliente(id,usuari,password,nom,dni,adreca,false):Cliente
nUsuario --> Registro: new_cliente
deactivate nUsuario
Registro -> Registro: clientes.add(new_cliente)
activate Registro
deactivate Registro
Registro --> TotSeries
deactivate Registro
TotSeries->Menu
deactivate Menu
@enduml
