@startuml
title	DS: Registrarse UC1
hide	footbox

actor Cliente
participant ":TotSeries" as TotSeries
participant ":Registro" as Registro
participant ":Usuario" as Usuario

participant "nuevo:Usuario" as nUsuario
participant ":Consola" as Consola

Cliente	-> TotSeries:registrar(nombre,usuario,pais,usuario,password,nacimiento)
activate TotSeries

note right TotSeries
        exist := true
    end note

loop  exist == true
    TotSeries -> Registro:exist:=hasUsuario(username:string):bool
    activate Registro
    note right Registro
        exist := false
    end note

    loop usuario in Registro
        Registro -> Usuario:getUsername():String
        activate Usuario
        Usuario  --> Registro:username_old
        deactivate Usuario
        opt username==username_old
            note right Registro
                exist := true
            end note
        end opt
    end loop

    Registro-->TotSeries:exist
    deactivate Registro
    opt exist ==true
        TotSeries -> Consola:escriu("Introduzca un nuevo username, el anterior ya existe")
        activate Consola
        TotSeries -> Consola:llegeixString():String
        Consola --> TotSeries:username := String
        deactivate Consola
    end opt
end loop

TotSeries -> Registro:registrar(nombre,usuario,pais,usuario,password,nacimiento)
activate Registro
create nUsuario
activate nUsuario
Registro -> nUsuario:Usuario(nombre,usuario,pais,usuario,password,nacimiento):Usuario
nUsuario --> Registro: new_usuario
deactivate nUsuario
Registro -> Registro: usuarios.add(new_usuario)
activate Registro
deactivate Registro
Registro --> TotSeries
deactivate Registro
TotSeries->"Consola":escriu("Usuario creado")
@enduml
