
@startuml
title	DS:4	Ver Episodio
hide	footbox

actor	Usuario

participant ":TotSeries" as TotSeries
participant ":Catalogo" as Catalogo
participant ":Serie" as Serie
participant ":Temporada" as Temporada
participant ":Episodio" as Episodio
participant "cliente:Cliente" as cliente
participant ":Factura" as factura
participant ":Consola" as Consola
participant ":Menu" as Menu
Usuario -> TotSeries:verEpisodio(serieId, temporadaId, episodioId):void
activate TotSeries
TotSeries -> Catalogo:existeEpisodio(serie_id,temporada_id,episodio_id):bool


activate Catalogo 
note right Catalogo
        exist := false
    end note
loop For serie in series

    Catalogo -> Serie:getId():Int
    activate Serie
    Serie --> Catalogo:id
    deactivate Serie


    opt id.equals(serie_id):bool
    Catalogo -> Serie:exist:=existeEpisodio(idTemporada,idEpisodio):bool
    activate Serie
    note right Serie
        exist := false
    end note
    
    loop For temporada in temporadas
        Serie -> Temporada:getId():Int
        activate Temporada
        Temporada --> Serie:id
        deactivate Temporada

        opt idTemporada==id
        Serie -> Temporada:exist:=existeEpisodio(idEpisodio):bool
        activate Temporada
        note right Temporada
            exist := false
        end note

        loop For episodio in episodios
            Temporada -> Episodio:getId():Int
            activate Episodio
            Episodio --> Temporada:id
            deactivate Episodio


            opt idEpisodio==id
                note right Temporada
                    exist := true
                end note
            end opt
        end loop
        Temporada --> Serie:exist
        end opt
    end loop
    deactivate Temporada
    Serie --> Catalogo:exist
    end opt
end loop

deactivate Serie
Catalogo --> TotSeries:exist
deactivate Catalogo
'
opt exist == true
    TotSeries -> Catalogo:verEpisodio(serie,temporada,episodio):Episodio
    activate Catalogo
    Catalogo -> Serie:verEpisodio(temporada,episodio):Episodio
    activate Serie
    Serie -> Temporada:verEpisodio(episodio):Episodio
    activate Temporada
    Temporada->Episodio:verEpisodio():Episodio
    activate Episodio
    Episodio->Temporada:Episodio
    deactivate Episodio
    Temporada->Serie:Episodio
    deactivate Temporada
    Serie -> Catalogo:Episodio
    deactivate Serie
    Catalogo -> TotSeries:Episodio
    deactivate Catalogo
    TotSeries -> Consola : visualizar(Episodio)
    ... Viendo episodio ...
    TotSeries->cliente:addVisualizacion():Void
    activate cliente
    cliente->factura:addVisualizacion():Void
    activate factura
    deactivate factura
    factura->cliente
    deactivate cliente
    cliente->TotSeries
    TotSeries --> Menu 
end opt
    TotSeries --> Menu
    deactivate TotSeries
    activate Menu
    
    Menu->Consola:escriure("Quiere valorar el episodio? Escribe true para valorar:"):Void
    Consola -> Menu:llegirString():String
    Consola --> Menu:opcion

    opt opcion == true
        note left Menu
        DS5. Valoracion
        end note
     end opt

deactivate TotSeries
@enduml
