@startuml
title		Cargar Datos
hide	footbox

actor	Usuario as usuario
participant "vista:Vista" as vista
participant "dataManager:TotSeriesDataManager" as data
participant "controlador:TotSeries" as totseries

usuario -> vista : CargarDatos
activate vista
note right vista
    el usuario busca el fichero
    por una ventana de navegacion
    de sistema.
end note
vista->data : obtenirDades(file)
activate data
data -> vista
deactivate data
vista -> data : cargarDatos(controlador):TotSeries
activate data
data -> totseries : setCatalogo(catalogo)
activate totseries
totseries -> data
deactivate totseries

data -> vista : controlador := control
deactivate data
vista -> vista: actualizarAll()
vista -> usuario
deactivate vista

@enduml