@startuml
user	->	TotSeries:seleccionaEpisodio()
TotSeries --> user: Mostrar Vista reproductor

note right TotSeries
    boolean reproducido=False
    boolean valorado=False
end note
loop pulsaBotonCancelar()
    opt pulsaBotonreproducir() and !reproducido
        TotSeries --> user :reproduccion
            ... Viendo episodio ...
    end opt
    
    opt valorarEpisodio() and reproducido and !valorado
            user	->	TotSeries:introducirNota()
            TotSeries --> user: "Se realizo la valoracion"
    end opt             
end loop
@enduml