@startuml
title	DSS5 Valoracion	
hide	footbox

actor	Usuario	as	user
participant ":Totseries" as Totseries
participant ":Consola" as consola
participant "nueva:Valoracion" as valoracion
participant "episodio:Episodio" as episodio
activate Totseries
note right Totseries
    episodio:Episodio
    puntuacion:Int
    usuario:String
end note

Totseries -> consola :escriu("Introduzca su usuario")
activate consola
consola -> Totseries :usuario:=llegeixString():String
Totseries -> consola :escriu("Introduzca puntuacion")
consola -> Totseries :puntuacion:=llegeixInt():Int
deactivate consola


create valoracion
activate valoracion
Totseries -> valoracion:Valoracion(usuario,puntuacion,fecha):Valoracion
valoracion --> Totseries: valoracion:=Valoracion
deactivate valoracion
Totseries -> episodio: episodio.setValoracion(valoracion):void
activate episodio
episodio -> episodio:addValoracion(valoracion):Void
episodio->Totseries
deactivate episodio

@enduml