@startuml
title	DSS5 Valoracion	
hide	footbox

actor	Usuario	as	user
participant "Menu" as menu
participant ":Totseries" as TotSeries
participant "nueva:Valoracion" as valoracion
participant ":Catalago" as Catalogo
participant ":Serie" as Serie
participant ":Temporada" as Temporada
participant "Episodio" as Episodio
activate menu
    menu -> TotSeries :valorarEpisodio(serieId, temporadaId, episodioId, puntuacion)
activate TotSeries
  TotSeries -> Catalogo:verEpisodio(serie,temporada,episodio):Episodio
    activate Catalogo
    Catalogo -> Serie:verEpisodio(temporada,episodio):Episodio
    activate Serie
    Serie -> Temporada:verEpisodio(episodio):Episodio
    activate Temporada
    Temporada->Episodio:verEpisodio():Episodio
    activate Episodio
    Episodio->Temporada:Episodio
    deactivate Episodio
    Temporada->Serie:Episodio
    deactivate Temporada
    Serie -> Catalogo:Episodio
    deactivate Serie
    Catalogo -> TotSeries:Episodio
    deactivate Catalogo


create valoracion
activate valoracion
TotSeries -> valoracion:Valoracion(actualCliente.getId(), puntuacion):Valoracion
valoracion --> TotSeries: valoracion:=Valoracion
deactivate valoracion
TotSeries -> Episodio: episodio.addValoracion(valoracion):void
activate Episodio
Episodio -> Episodio:addValoracion(valoracion):Void
Episodio->TotSeries
deactivate Episodio
TotSeries --> menu
deactivate TotSeries
@enduml
