@startuml
'left to right direction

title Diagrama de Dominio para TotSeries

object Totseries

object Episodio {
idEpisodio
nombre
duracion
idioma
fecha
descripción
}

object Artista {
id
nombre
nacionalidad
}

object Productora {
nombre
identificador
añoCreacion
}

object Cliente {
nacionalidad
fechaNacimiento
}

object Factura{
total
fecha
}

object Temporada{
id
numEpisodios
}

object Serie{
id
descripcion
titulo
numTemporadas
}

object Usuario{
nombre
username
password
id
}

object Anonimo{
}

object Valoracion{
puntuacion
fecha
}


object Reproduccion{
username
date
}
object Catalogo
object Tiempo
object VIP
object ActividadEstado
object Active
object Idle
object Administrador
object Actor
object Director
object Estado
object Registro

Totseries "1" -- "1" Catalogo : tiene >
Totseries "1" -- "1" Registro : tiene >
Totseries "1" -- "*" Anonimo : tiene >

Registro "1" -- "*" Usuario : tiene >
Usuario <|-- Cliente
Usuario <|- Administrador

Usuario "*" -- "1" Catalogo : visualiza >
Anonimo "*" -- "1" Catalogo : visualiza >

Cliente "1" -- "*" Factura : tiene >
Cliente "1" -- "*" Valoracion : ha realizado >
Cliente "*" -- "1" Estado : es >
Cliente "*" -- "1" ActividadEstado : esta >
ActividadEstado <|-- Active
ActividadEstado <|-- Idle

Estado <|-- VIP
Estado <|-- Basico

Administrador "1" - "1" Estado : cambia >

Catalogo "1" *-- "1..*" Serie : consta >

Serie "1" *-- "1..*" Temporada : consta >
Serie "1..*" -- "1..*" Artista : tiene >
Serie "1..*"-- "1..*" Productora : tiene >
Serie "1"-- "*" Reproduccion : tiene >

Artista  <|-- Actor
Artista  <|-- Director

Temporada "1" *-- "1..*" Episodio : consta >

Episodio "0..1" -- "*" Cliente : visualiza <
Episodio "1" -- "*" Valoracion : tiene >

Factura "*" -- "1" Tiempo : genera <

@enduml
